export { default as HomeHeroMobile } from "./home-hero-mobile.jpg";
export { default as HomeHeroTablet } from "./home-hero-tablet.jpg";
export { default as HomeHeroDesktop } from "./home-hero-desktop.jpg";
export { default as Telemetry } from "./telemetry.jpg";
export { default as NearYou } from "./near-you.jpg";
export { default as Payments } from "./payments.jpg";
export { default as FooterMobile } from "./footer-mobile.png";
export { default as FooterTablet } from "./footer-tablet.png";
export { default as FooterDesktop } from "./footer-desktop.png";
